### ISSUE TITLE
Capacitor Integration

### ISSUE THREAD

**Issue by Kaoschuks** [mozhn/cordova-plugin-agoracall#1]
Hello,
How do I integrate this plugin to ionic capacitor?.

I tried npm I --save https://github.com/mozhn/cordova-plugin-agoracall

the plugin shows but not showing any interface for android.

please help

**Comment by mozhn** [comment]
Plugin is not yet complete for video calling. Only audio call is working.

**Comment by Kaoschuks** [comment]
I get so how do I:

- integrate for ionic capacitor.
- start audio call
- connect to a call
etc....

**Comment by mozhn** [comment]
Integration steps:

1. npm I --save https://github.com/mozhn/cordova-plugin-agoracall
2. First call [init](https://github.com/mozhn/cordova-plugin-agoracall/blob/c62a22980ac02f2c43553c3d0962d4127d7abde5/www/AgoraCall.js#L3) method 
3. Engine initialize after call [join](https://github.com/mozhn/cordova-plugin-agoracall/blob/c62a22980ac02f2c43553c3d0962d4127d7abde5/www/AgoraCall.js#L7)

Example:

init:
```
    cordova.plugins.AgoraCall.init(environment.agoraAppId, (event: string) => {
      if (event === 'ENGINE_CREATED') {
        this.joinChannel(threadId);
      } else if (event === 'CONNECTED') {
        this.deviceState$.next('waiting-participant');
      } else if (event === 'PARTICIPANT_CONNECTED') {
        this.deviceState$.next('connected-participant');
      } else if (event === 'PARTICIPANT_DISCONNECTED') {
        this.closeChannel(threadId);
      }
    });
```

join:
```
  private async joinChannel(threadId: string) {
    const tokenResult = await this.createAccessToken(threadId);
    cordova.plugins.AgoraCall.join(tokenResult.token, threadId, tokenResult.uid);
  }
```

Note: This plugin does not provide a visual interface.
